#! /bin/bash

# Makes py-qt based python viewers from xml files (.ui) generated by Qt-designer.

inpath=../uis
for filename in $inpath/*.ui; do
    in=$filename
    out=${filename/uis/viewers}
    out=${out::-3}.py
    pyuic4 -x $in -o $out
done

