# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/plot_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1032, 381)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_enveloppes = QtGui.QHBoxLayout()
        self.horizontalLayout_enveloppes.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_enveloppes.setObjectName(_fromUtf8("horizontalLayout_enveloppes"))
        self.pushButton_addCurve = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addCurve.sizePolicy().hasHeightForWidth())
        self.pushButton_addCurve.setSizePolicy(sizePolicy)
        self.pushButton_addCurve.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_addCurve.setObjectName(_fromUtf8("pushButton_addCurve"))
        self.horizontalLayout_enveloppes.addWidget(self.pushButton_addCurve)
        self.label_enveloppes = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_enveloppes.sizePolicy().hasHeightForWidth())
        self.label_enveloppes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_enveloppes.setFont(font)
        self.label_enveloppes.setObjectName(_fromUtf8("label_enveloppes"))
        self.horizontalLayout_enveloppes.addWidget(self.label_enveloppes)
        self.line_2 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_enveloppes.addWidget(self.line_2)
        self.pushButton_killAllCurves = QtGui.QPushButton(Form)
        self.pushButton_killAllCurves.setEnabled(True)
        self.pushButton_killAllCurves.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_killAllCurves.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_killAllCurves.setObjectName(_fromUtf8("pushButton_killAllCurves"))
        self.horizontalLayout_enveloppes.addWidget(self.pushButton_killAllCurves)
        self.verticalLayout.addLayout(self.horizontalLayout_enveloppes)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(960, 0))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_singleCurve = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_singleCurve.sizePolicy().hasHeightForWidth())
        self.frame_singleCurve.setSizePolicy(sizePolicy)
        self.frame_singleCurve.setMinimumSize(QtCore.QSize(960, 0))
        self.frame_singleCurve.setBaseSize(QtCore.QSize(0, 10))
        self.frame_singleCurve.setFrameShape(QtGui.QFrame.Box)
        self.frame_singleCurve.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_singleCurve.setObjectName(_fromUtf8("frame_singleCurve"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_singleCurve)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_singleCurve = QtGui.QVBoxLayout()
        self.verticalLayout_singleCurve.setObjectName(_fromUtf8("verticalLayout_singleCurve"))
        self.verticalLayout_3.addLayout(self.verticalLayout_singleCurve)
        self.verticalLayout.addWidget(self.frame_singleCurve)
        spacerItem1 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_refPoints = QtGui.QHBoxLayout()
        self.horizontalLayout_refPoints.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_refPoints.setObjectName(_fromUtf8("horizontalLayout_refPoints"))
        self.pushButton_addRefPoint = QtGui.QPushButton(Form)
        self.pushButton_addRefPoint.setMaximumSize(QtCore.QSize(28, 16777215))
        self.pushButton_addRefPoint.setObjectName(_fromUtf8("pushButton_addRefPoint"))
        self.horizontalLayout_refPoints.addWidget(self.pushButton_addRefPoint)
        self.label_RefPoints = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RefPoints.sizePolicy().hasHeightForWidth())
        self.label_RefPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_RefPoints.setFont(font)
        self.label_RefPoints.setObjectName(_fromUtf8("label_RefPoints"))
        self.horizontalLayout_refPoints.addWidget(self.label_RefPoints)
        self.line = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_refPoints.addWidget(self.line)
        self.pushButton_openRefPoints = QtGui.QPushButton(Form)
        self.pushButton_openRefPoints.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_openRefPoints.setObjectName(_fromUtf8("pushButton_openRefPoints"))
        self.horizontalLayout_refPoints.addWidget(self.pushButton_openRefPoints)
        self.pushButton_killAllRefPoints = QtGui.QPushButton(Form)
        self.pushButton_killAllRefPoints.setEnabled(False)
        self.pushButton_killAllRefPoints.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_killAllRefPoints.setObjectName(_fromUtf8("pushButton_killAllRefPoints"))
        self.horizontalLayout_refPoints.addWidget(self.pushButton_killAllRefPoints)
        self.verticalLayout.addLayout(self.horizontalLayout_refPoints)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setMinimumSize(QtCore.QSize(28, 0))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_points_settings = QtGui.QVBoxLayout()
        self.verticalLayout_points_settings.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_points_settings.setSpacing(6)
        self.verticalLayout_points_settings.setObjectName(_fromUtf8("verticalLayout_points_settings"))
        self.horizontalLayout.addLayout(self.verticalLayout_points_settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_Go = QtGui.QGridLayout()
        self.gridLayout_Go.setObjectName(_fromUtf8("gridLayout_Go"))
        self.widget_showParams = QtGui.QWidget(Form)
        self.widget_showParams.setObjectName(_fromUtf8("widget_showParams"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_showParams)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_legend = QtGui.QRadioButton(self.widget_showParams)
        self.radioButton_legend.setAutoExclusive(False)
        self.radioButton_legend.setObjectName(_fromUtf8("radioButton_legend"))
        self.verticalLayout_5.addWidget(self.radioButton_legend)
        self.radioButton_pointRange = QtGui.QRadioButton(self.widget_showParams)
        self.radioButton_pointRange.setChecked(False)
        self.radioButton_pointRange.setObjectName(_fromUtf8("radioButton_pointRange"))
        self.verticalLayout_5.addWidget(self.radioButton_pointRange)
        self.radioButton_title = QtGui.QRadioButton(self.widget_showParams)
        self.radioButton_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_title.setAutoExclusive(False)
        self.radioButton_title.setObjectName(_fromUtf8("radioButton_title"))
        self.verticalLayout_5.addWidget(self.radioButton_title)
        self.gridLayout_Go.addWidget(self.widget_showParams, 0, 0, 1, 1)
        self.pushButton_plotOne = QtGui.QPushButton(Form)
        self.pushButton_plotOne.setMaximumSize(QtCore.QSize(90, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../images/icon_plotOne.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_plotOne.setIcon(icon)
        self.pushButton_plotOne.setObjectName(_fromUtf8("pushButton_plotOne"))
        self.gridLayout_Go.addWidget(self.pushButton_plotOne, 0, 1, 1, 1)
        self.widget_dummy = QtGui.QWidget(Form)
        self.widget_dummy.setObjectName(_fromUtf8("widget_dummy"))
        self.gridLayout_Go.addWidget(self.widget_dummy, 0, 3, 1, 1)
        self.pushButton_plotAll = QtGui.QPushButton(Form)
        self.pushButton_plotAll.setMaximumSize(QtCore.QSize(90, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../images/icon_plotAll.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_plotAll.setIcon(icon1)
        self.pushButton_plotAll.setObjectName(_fromUtf8("pushButton_plotAll"))
        self.gridLayout_Go.addWidget(self.pushButton_plotAll, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_Go)
        spacerItem3 = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton_addCurve.setToolTip(_translate("Form", "Add a new curve", None))
        self.pushButton_addCurve.setText(_translate("Form", "+", None))
        self.label_enveloppes.setText(_translate("Form", "Critical enveloppes", None))
        self.pushButton_killAllCurves.setToolTip(_translate("Form", "Delete all curves", None))
        self.pushButton_killAllCurves.setText(_translate("Form", "Clear all", None))
        self.pushButton_addRefPoint.setToolTip(_translate("Form", "Add a new reference point", None))
        self.pushButton_addRefPoint.setText(_translate("Form", "+", None))
        self.label_RefPoints.setText(_translate("Form", "Reference points", None))
        self.pushButton_openRefPoints.setToolTip(_translate("Form", "Import reference points from (x, y) data", None))
        self.pushButton_openRefPoints.setText(_translate("Form", "Import", None))
        self.pushButton_killAllRefPoints.setToolTip(_translate("Form", "Delete all reference points", None))
        self.pushButton_killAllRefPoints.setText(_translate("Form", "Clear all", None))
        self.radioButton_legend.setToolTip(_translate("Form", "Check to add legend on plot", None))
        self.radioButton_legend.setText(_translate("Form", "show legend", None))
        self.radioButton_pointRange.setToolTip(_translate("Form", "Check to show range as a light gray line under curve points", None))
        self.radioButton_pointRange.setText(_translate("Form", "show curve point range", None))
        self.radioButton_title.setToolTip(_translate("Form", "Check to add title resuming constant parameters", None))
        self.radioButton_title.setText(_translate("Form", "constant parameters as title", None))
        self.pushButton_plotOne.setToolTip(_translate("Form", "Plot current curve and reference points (Crtl+P)", None))
        self.pushButton_plotOne.setText(_translate("Form", "Plot", None))
        self.pushButton_plotOne.setShortcut(_translate("Form", "Ctrl+P", None))
        self.pushButton_plotAll.setToolTip(_translate("Form", "Plot all curves and points (Crtl+A)", None))
        self.pushButton_plotAll.setText(_translate("Form", "Plot all", None))
        self.pushButton_plotAll.setShortcut(_translate("Form", "Ctrl+A", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

