# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/calculator_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(985, 837)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_draw = QtGui.QHBoxLayout()
        self.horizontalLayout_draw.setObjectName(_fromUtf8("horizontalLayout_draw"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_draw.addItem(spacerItem)
        self.label_draw = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_draw.sizePolicy().hasHeightForWidth())
        self.label_draw.setSizePolicy(sizePolicy)
        self.label_draw.setMaximumSize(QtCore.QSize(600, 250))
        self.label_draw.setFrameShape(QtGui.QFrame.Box)
        self.label_draw.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_draw.setText(_fromUtf8(""))
        self.label_draw.setPixmap(QtGui.QPixmap(_fromUtf8(":/illustrations/illustration_calculator.png")))
        self.label_draw.setScaledContents(True)
        self.label_draw.setObjectName(_fromUtf8("label_draw"))
        self.horizontalLayout_draw.addWidget(self.label_draw)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_draw.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_draw)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(19, 107, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.groupBox_parameters = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_parameters.sizePolicy().hasHeightForWidth())
        self.groupBox_parameters.setSizePolicy(sizePolicy)
        self.groupBox_parameters.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_parameters.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_parameters.setObjectName(_fromUtf8("groupBox_parameters"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_parameters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_beta = QtGui.QHBoxLayout()
        self.horizontalLayout_beta.setSpacing(0)
        self.horizontalLayout_beta.setObjectName(_fromUtf8("horizontalLayout_beta"))
        self.gridLayout.addLayout(self.horizontalLayout_beta, 1, 4, 1, 1)
        self.radioButton_alpha = QtGui.QRadioButton(self.groupBox_parameters)
        self.radioButton_alpha.setMaximumSize(QtCore.QSize(20, 16777215))
        self.radioButton_alpha.setText(_fromUtf8(""))
        self.radioButton_alpha.setChecked(True)
        self.radioButton_alpha.setObjectName(_fromUtf8("radioButton_alpha"))
        self.gridLayout.addWidget(self.radioButton_alpha, 0, 0, 1, 1)
        self.radioButton_beta = QtGui.QRadioButton(self.groupBox_parameters)
        self.radioButton_beta.setMaximumSize(QtCore.QSize(20, 16777215))
        self.radioButton_beta.setText(_fromUtf8(""))
        self.radioButton_beta.setObjectName(_fromUtf8("radioButton_beta"))
        self.gridLayout.addWidget(self.radioButton_beta, 1, 0, 1, 1)
        self.radioButton_phiD = QtGui.QRadioButton(self.groupBox_parameters)
        self.radioButton_phiD.setMaximumSize(QtCore.QSize(20, 16777215))
        self.radioButton_phiD.setText(_fromUtf8(""))
        self.radioButton_phiD.setObjectName(_fromUtf8("radioButton_phiD"))
        self.gridLayout.addWidget(self.radioButton_phiD, 1, 5, 1, 1)
        self.horizontalLayout_alpha = QtGui.QHBoxLayout()
        self.horizontalLayout_alpha.setSpacing(0)
        self.horizontalLayout_alpha.setObjectName(_fromUtf8("horizontalLayout_alpha"))
        self.gridLayout.addLayout(self.horizontalLayout_alpha, 0, 4, 1, 1)
        self.radioButton_phiB = QtGui.QRadioButton(self.groupBox_parameters)
        self.radioButton_phiB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.radioButton_phiB.setText(_fromUtf8(""))
        self.radioButton_phiB.setObjectName(_fromUtf8("radioButton_phiB"))
        self.gridLayout.addWidget(self.radioButton_phiB, 0, 5, 1, 1)
        self.label_phiD = QtGui.QLabel(self.groupBox_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_phiD.sizePolicy().hasHeightForWidth())
        self.label_phiD.setSizePolicy(sizePolicy)
        self.label_phiD.setMaximumSize(QtCore.QSize(20, 24))
        self.label_phiD.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_phiD.png")))
        self.label_phiD.setScaledContents(True)
        self.label_phiD.setObjectName(_fromUtf8("label_phiD"))
        self.gridLayout.addWidget(self.label_phiD, 1, 6, 1, 1)
        self.label_phiB = QtGui.QLabel(self.groupBox_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_phiB.sizePolicy().hasHeightForWidth())
        self.label_phiB.setSizePolicy(sizePolicy)
        self.label_phiB.setMaximumSize(QtCore.QSize(20, 24))
        self.label_phiB.setText(_fromUtf8(""))
        self.label_phiB.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_phiB.png")))
        self.label_phiB.setScaledContents(True)
        self.label_phiB.setObjectName(_fromUtf8("label_phiB"))
        self.gridLayout.addWidget(self.label_phiB, 0, 6, 1, 1)
        self.horizontalLayout_phiD = QtGui.QHBoxLayout()
        self.horizontalLayout_phiD.setSpacing(0)
        self.horizontalLayout_phiD.setObjectName(_fromUtf8("horizontalLayout_phiD"))
        self.gridLayout.addLayout(self.horizontalLayout_phiD, 1, 7, 1, 1)
        self.horizontalLayout_phiB = QtGui.QHBoxLayout()
        self.horizontalLayout_phiB.setSpacing(0)
        self.horizontalLayout_phiB.setObjectName(_fromUtf8("horizontalLayout_phiB"))
        self.gridLayout.addLayout(self.horizontalLayout_phiB, 0, 7, 1, 1)
        self.label_alpha = QtGui.QLabel(self.groupBox_parameters)
        self.label_alpha.setMaximumSize(QtCore.QSize(12, 24))
        self.label_alpha.setText(_fromUtf8(""))
        self.label_alpha.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_alpha.png")))
        self.label_alpha.setScaledContents(True)
        self.label_alpha.setObjectName(_fromUtf8("label_alpha"))
        self.gridLayout.addWidget(self.label_alpha, 0, 1, 1, 1)
        self.label_beta = QtGui.QLabel(self.groupBox_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_beta.sizePolicy().hasHeightForWidth())
        self.label_beta.setSizePolicy(sizePolicy)
        self.label_beta.setMaximumSize(QtCore.QSize(12, 24))
        self.label_beta.setText(_fromUtf8(""))
        self.label_beta.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_beta.png")))
        self.label_beta.setScaledContents(True)
        self.label_beta.setObjectName(_fromUtf8("label_beta"))
        self.gridLayout.addWidget(self.label_beta, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_parameters)
        self.groupBox_fluids = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_fluids.sizePolicy().hasHeightForWidth())
        self.groupBox_fluids.setSizePolicy(sizePolicy)
        self.groupBox_fluids.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_fluids.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_fluids.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_fluids.setCheckable(True)
        self.groupBox_fluids.setChecked(False)
        self.groupBox_fluids.setObjectName(_fromUtf8("groupBox_fluids"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_fluids)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_lamdaB = QtGui.QLabel(self.groupBox_fluids)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lamdaB.sizePolicy().hasHeightForWidth())
        self.label_lamdaB.setSizePolicy(sizePolicy)
        self.label_lamdaB.setMaximumSize(QtCore.QSize(30, 24))
        self.label_lamdaB.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_lamdaB.png")))
        self.label_lamdaB.setScaledContents(True)
        self.label_lamdaB.setObjectName(_fromUtf8("label_lamdaB"))
        self.gridLayout_2.addWidget(self.label_lamdaB, 0, 0, 1, 1)
        self.horizontalLayout_lamdaB = QtGui.QHBoxLayout()
        self.horizontalLayout_lamdaB.setSpacing(0)
        self.horizontalLayout_lamdaB.setObjectName(_fromUtf8("horizontalLayout_lamdaB"))
        self.gridLayout_2.addLayout(self.horizontalLayout_lamdaB, 0, 1, 1, 1)
        self.label_rhof = QtGui.QLabel(self.groupBox_fluids)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rhof.sizePolicy().hasHeightForWidth())
        self.label_rhof.setSizePolicy(sizePolicy)
        self.label_rhof.setMaximumSize(QtCore.QSize(24, 24))
        self.label_rhof.setText(_fromUtf8(""))
        self.label_rhof.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_rhof.png")))
        self.label_rhof.setScaledContents(True)
        self.label_rhof.setObjectName(_fromUtf8("label_rhof"))
        self.gridLayout_2.addWidget(self.label_rhof, 0, 2, 1, 1)
        self.horizontalLayout_rhof = QtGui.QHBoxLayout()
        self.horizontalLayout_rhof.setSpacing(0)
        self.horizontalLayout_rhof.setObjectName(_fromUtf8("horizontalLayout_rhof"))
        self.gridLayout_2.addLayout(self.horizontalLayout_rhof, 0, 3, 1, 1)
        self.label_lamdaD = QtGui.QLabel(self.groupBox_fluids)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lamdaD.sizePolicy().hasHeightForWidth())
        self.label_lamdaD.setSizePolicy(sizePolicy)
        self.label_lamdaD.setMaximumSize(QtCore.QSize(30, 24))
        self.label_lamdaD.setText(_fromUtf8(""))
        self.label_lamdaD.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_lamdaD.png")))
        self.label_lamdaD.setScaledContents(True)
        self.label_lamdaD.setObjectName(_fromUtf8("label_lamdaD"))
        self.gridLayout_2.addWidget(self.label_lamdaD, 1, 0, 1, 1)
        self.horizontalLayout_lamdaD = QtGui.QHBoxLayout()
        self.horizontalLayout_lamdaD.setSpacing(0)
        self.horizontalLayout_lamdaD.setObjectName(_fromUtf8("horizontalLayout_lamdaD"))
        self.gridLayout_2.addLayout(self.horizontalLayout_lamdaD, 1, 1, 1, 1)
        self.label_rhosr = QtGui.QLabel(self.groupBox_fluids)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rhosr.sizePolicy().hasHeightForWidth())
        self.label_rhosr.setSizePolicy(sizePolicy)
        self.label_rhosr.setMaximumSize(QtCore.QSize(24, 24))
        self.label_rhosr.setText(_fromUtf8(""))
        self.label_rhosr.setPixmap(QtGui.QPixmap(_fromUtf8(":/params/params_rhosr.png")))
        self.label_rhosr.setScaledContents(True)
        self.label_rhosr.setObjectName(_fromUtf8("label_rhosr"))
        self.gridLayout_2.addWidget(self.label_rhosr, 1, 2, 1, 1)
        self.horizontalLayout_rhosr = QtGui.QHBoxLayout()
        self.horizontalLayout_rhosr.setSpacing(0)
        self.horizontalLayout_rhosr.setObjectName(_fromUtf8("horizontalLayout_rhosr"))
        self.gridLayout_2.addLayout(self.horizontalLayout_rhosr, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_fluids)
        spacerItem4 = QtGui.QSpacerItem(20, 107, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_context = QtGui.QHBoxLayout()
        self.horizontalLayout_context.setObjectName(_fromUtf8("horizontalLayout_context"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_context.addItem(spacerItem5)
        self.verticalLayout_context = QtGui.QVBoxLayout()
        self.verticalLayout_context.setObjectName(_fromUtf8("verticalLayout_context"))
        self.horizontalLayout_context.addLayout(self.verticalLayout_context)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_context.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_context)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_GoClear = QtGui.QHBoxLayout()
        self.horizontalLayout_GoClear.setObjectName(_fromUtf8("horizontalLayout_GoClear"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_GoClear.addItem(spacerItem8)
        self.pushButton_Go = QtGui.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/button_compute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Go.setIcon(icon)
        self.pushButton_Go.setObjectName(_fromUtf8("pushButton_Go"))
        self.horizontalLayout_GoClear.addWidget(self.pushButton_Go)
        self.pushButton_Clear = QtGui.QPushButton(Form)
        self.pushButton_Clear.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_Clear.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_Clear.setObjectName(_fromUtf8("pushButton_Clear"))
        self.horizontalLayout_GoClear.addWidget(self.pushButton_Clear)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_GoClear.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_GoClear)
        self.horizontalLayout_Results = QtGui.QHBoxLayout()
        self.horizontalLayout_Results.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_Results.setObjectName(_fromUtf8("horizontalLayout_Results"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_Results.addItem(spacerItem10)
        self.textEdit_results = QtGui.QTextEdit(Form)
        self.textEdit_results.setMinimumSize(QtCore.QSize(600, 200))
        self.textEdit_results.setMaximumSize(QtCore.QSize(600, 16777215))
        self.textEdit_results.setToolTip(_fromUtf8(""))
        self.textEdit_results.setReadOnly(True)
        self.textEdit_results.setObjectName(_fromUtf8("textEdit_results"))
        self.horizontalLayout_Results.addWidget(self.textEdit_results)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_Results.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_Results)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_parameters.setTitle(_translate("Form", "Select parameter to calculate", None))
        self.radioButton_alpha.setToolTip(_translate("Form", "Check for calculate critical surface slope", None))
        self.radioButton_beta.setToolTip(_translate("Form", "Check for calculate basal slope", None))
        self.radioButton_phiD.setToolTip(_translate("Form", "Check for calculate basal friction angle", None))
        self.radioButton_phiB.setToolTip(_translate("Form", "Check for calculate bulk friction angle", None))
        self.label_phiD.setToolTip(_translate("Form", "Basal friction angle [deg]", None))
        self.label_phiB.setToolTip(_translate("Form", "Bulk friction angle [deg]", None))
        self.label_alpha.setToolTip(_translate("Form", "Critical surface slope [deg]", None))
        self.label_beta.setToolTip(_translate("Form", "Basal slope [deg]", None))
        self.groupBox_fluids.setToolTip(_translate("Form", "Check to activate fluids pore pressure parameters", None))
        self.groupBox_fluids.setTitle(_translate("Form", "Fluids pore pressure", None))
        self.label_lamdaB.setToolTip(_translate("Form", "Bulk fluids overpressure ratio", None))
        self.label_rhof.setToolTip(_translate("Form", "Volumetric mass density of fluids", None))
        self.label_lamdaD.setToolTip(_translate("Form", "Bulk fluids overpressure ratio", None))
        self.label_rhosr.setToolTip(_translate("Form", "Volumetric mass density of saturated rock", None))
        self.pushButton_Go.setToolTip(_translate("Form", "Launch calculation (Crtl+G)", None))
        self.pushButton_Go.setText(_translate("Form", "Go", None))
        self.pushButton_Go.setShortcut(_translate("Form", "Ctrl+G", None))
        self.pushButton_Clear.setToolTip(_translate("Form", "Clear inputs and results fields", None))
        self.pushButton_Clear.setText(_translate("Form", "Clear", None))
        self.textEdit_results.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import eccw.images.ressources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

